version: '3.7'

services:
  backend:
    container_name: rest-api
    build: ./rest-api
    ports:
      - 8080:80
    env_file:
      - rest-api/prod.env
    volumes:
      - ./rest-api:/backend
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Build.Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8080
    env_file:
      - ./frontend/.env
    environment:
      CHOKIDAR_USEPOLLING: "true"  
    stdin_open: true
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 80:80