version: '3.7'

services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    env_file:
      - rest-api/.env
  frontend:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000