version: '3.7'

services:
  backend:
    build: ./rest-api
    ports:
      - 8080:8080
    env_file:
      - rest-api/.env
    volumes:
      - ./rest-api:/backend
  frontend:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      API_URL: "localhost:8080"
    stdin_open: true
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000